### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by MithrandirCraft** [James137137/FactionChat#16] opened 2016-01-30 00:00 UTC
Found this error on logs:
http://hastebin.com/cuxawahoje.avrasm

Spigot version: 1.8.8
Faction chat version: 1.8.12

**Comment by Barrimor** [comment] 2016-02-03 08:57
Caused by: java.lang.IllegalArgumentException: NPCs are not allowed: CraftPlayer{name=AndresGatoXD}

Do you have an AntiCheat or something that add "Citizens" or else?

**Comment by MithrandirCraft** [comment] 2016-02-04 15:59
Hmmm I used to have AntiAura (premium spigot) plugin. But I removed it because it's quite buggy. I don't remember if I had it on at that moment, but I think not.

**Comment by MithrandirCraft** [comment] 2016-02-04 16:00
Now I'm just using NCP, which doesn't use NPC's

**Comment by James137137** [comment] 2016-02-05 04:56
no idea what the NPC is but I've made a check before hand so it doesn't error. Lets hope it works...

**Comment by MithrandirCraft** [comment] 2016-02-05 16:33
NCP = NoCheatPlus

**Comment by James137137** [comment] 2016-04-06 22:48
I think this is fixed now

**Closed** 2016-04-06 22:48 UTC
